env:
    #credentials: "ENCRYPTED[4526be3acf95a0d69e63c2024f61eacc9becd1b166eb4c671a0f62030a7927284dab21b9a07ba52c425948ff430e8727]"
    rcloneconfig: "ENCRYPTED[!27cdb38b9c9e4beaf0a9c9c2852cb8a41b7f0dd7bc44ed2c940b9f35d61592a1d4a845f3ca7e3ff445e8caef07ba14a6!]"
    tokentl: "ENCRYPTED[!4a0d8baed758cb2afd823cb0b80f7fa39e512752110df7188eb14a5390115eddded8133c873651742e28e221f25b0e93!]"
    idtl: "ENCRYPTED[!c75265493c359f33c43c1e996ad66d70efbd0a28670b8ffbf9cba43036dacde06c6ae879a2b0177d9f6164eda8fec5d9!]"
    lunch: lunch lineage_sweet-userdebug
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "phoenix-1708"
       - git config --global user.email "harikumar1708@gmail.com"
       #- echo "$credentials" > ~/.git-credentials
       #- git config --global credential.helper store --file=~/.git-credentials
       - sudo apt-get install -y wget
       - sudo apt-get install -y curl
       - cd /tmp
       - mkdir rom
       #- rclone copy remote:ccache/ci2/ccache.tar.gz /tmp -P
       #- cd /tmp
       - mkdir ccache
       #- curl https://oshi.at/YtQE -O ccache.tar.gz
       - wget https://oshi.at/YtQE -O ccache.tar.gz --show-progress
       - time tar xf ccache.tar.gz
       #- cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/RiceDroid/android -b thirteen -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync
      # DT/VT/KT/TC
      - git clone https://github.com/phoenix-1708/device_sweet -b main --depth=1 device/xiaomi/sweet
      - git clone https://github.com/phoenix-1708/vendor_sweet -b main --depth=1 vendor/xiaomi/sweet
      - git clone https://github.com/phoenix-1708/kernel_xiaomi_sm6150 -b t13 --depth=1 kernel/xiaomi/sweet
      # HALS
      - rm -rf prebuilts/clang/host/linux-x86/clang-r450784d
      - git clone https://gitlab.com/ImSurajxD/clang-r450784d -b master --depth=1 prebuilts/clang/host/linux-x86/clang-r450784d
      - git clone https://gitlab.com/nerdprojectorg/SDClang -b 16 --depth=1 prebuilts/clang/host/linux-x86/clang-sdclang
      - cp kernel/xiaomi/sweet/arch/arm64/configs/sweet_defconfig kernel/xiaomi/sweet/arch/arm64/configs/sweet_user_defconfig
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip)"
      #- rclone copy /tmp/rom/out/target/product/sweet/*.zip remote:sweet -P
      - curl -T /tmp/rom/out/target/product/sweet/*.zip https://oshi.at
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/sweet/ && ls *.zip) Uploaded Successfully!"
      #- curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Download link http://anu.inok189.workers.dev/juice/$(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip)"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      #- rclone copy ccache.tar.gz remote:ccache/ci2 -P
      - curl -T ccache.tar.gz https://oshi.at
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
